# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8010
  connection-timeout: 5000ms
  servlet:
    context-path: /admin

spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  mvc:
    throw-exception-if-no-handler-found: true
#  resources:
#    add-mappings: false
#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: io.live_mall.modules.*.entity
  global-config:
    refresh-mapper: true
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

txai:
   secretId: AKIDA6A6mSLDfwUmnXJDDwNYv1rRl32mI7h0
   secretKey: xg9MIxQffbHhrkMipgZCYeU5QWMIMBj0
sms:
  dingtalk:
    webhook: https://oapi.dingtalk.com/robot/send?access_token=639c8b9cbe01b2d664e5bfd69c2514ad145fb68da6efd554691eeae7fcb317d8
  aliyun:
    accessKey: LTAIDBZFGv7iRDNZ
    secretKey: Aml66x79qk3uP7mLVBtGP3Fez2qca8
    signName: 经销商综合服务平台
    channels:
      loginCodeChannel: SMS_164421053
      serviceStatusChange: SMS_60020339
      productSuc: SMS_209197438
      productRb: SMS_209162489
      productBack: SMS_209192479
      productCancel: SMS_209197424
      productAplly: SMS_209192471
renren:
  redis:
    open: true
  shiro:
    redis: true
  # APP模块，是通过jwt认证的，如果要使用APP模块，则需要修改【加密秘钥】
  jwt:
    # 加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5[www.renren.io]
    # token有效时长，7天，单位秒
    expire: 604800
    header: token
temp:
   path: E:\\work\\sxhl\\ipo\\five_way_ipo\\doc
